# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import disttag_pb2 as disttag__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in disttag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameMasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinGame = channel.unary_unary(
                '/disttag.GameMaster/JoinGame',
                request_serializer=disttag__pb2.PlayerInfo.SerializeToString,
                response_deserializer=disttag__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.ReportTag = channel.unary_unary(
                '/disttag.GameMaster/ReportTag',
                request_serializer=disttag__pb2.TagEvent.SerializeToString,
                response_deserializer=disttag__pb2.Ack.FromString,
                _registered_method=True)
        self.GetItPlayer = channel.unary_unary(
                '/disttag.GameMaster/GetItPlayer',
                request_serializer=disttag__pb2.Empty.SerializeToString,
                response_deserializer=disttag__pb2.ItInfo.FromString,
                _registered_method=True)


class GameMasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameMasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=disttag__pb2.PlayerInfo.FromString,
                    response_serializer=disttag__pb2.JoinResponse.SerializeToString,
            ),
            'ReportTag': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTag,
                    request_deserializer=disttag__pb2.TagEvent.FromString,
                    response_serializer=disttag__pb2.Ack.SerializeToString,
            ),
            'GetItPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItPlayer,
                    request_deserializer=disttag__pb2.Empty.FromString,
                    response_serializer=disttag__pb2.ItInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'disttag.GameMaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('disttag.GameMaster', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameMaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/disttag.GameMaster/JoinGame',
            disttag__pb2.PlayerInfo.SerializeToString,
            disttag__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/disttag.GameMaster/ReportTag',
            disttag__pb2.TagEvent.SerializeToString,
            disttag__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/disttag.GameMaster/GetItPlayer',
            disttag__pb2.Empty.SerializeToString,
            disttag__pb2.ItInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RegionServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Move = channel.unary_unary(
                '/disttag.RegionServer/Move',
                request_serializer=disttag__pb2.MoveRequest.SerializeToString,
                response_deserializer=disttag__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.AddPlayer = channel.unary_unary(
                '/disttag.RegionServer/AddPlayer',
                request_serializer=disttag__pb2.PlayerState.SerializeToString,
                response_deserializer=disttag__pb2.Ack.FromString,
                _registered_method=True)
        self.RemovePlayer = channel.unary_unary(
                '/disttag.RegionServer/RemovePlayer',
                request_serializer=disttag__pb2.PlayerId.SerializeToString,
                response_deserializer=disttag__pb2.Ack.FromString,
                _registered_method=True)


class RegionServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegionServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=disttag__pb2.MoveRequest.FromString,
                    response_serializer=disttag__pb2.MoveResponse.SerializeToString,
            ),
            'AddPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPlayer,
                    request_deserializer=disttag__pb2.PlayerState.FromString,
                    response_serializer=disttag__pb2.Ack.SerializeToString,
            ),
            'RemovePlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePlayer,
                    request_deserializer=disttag__pb2.PlayerId.FromString,
                    response_serializer=disttag__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'disttag.RegionServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('disttag.RegionServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegionServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/disttag.RegionServer/Move',
            disttag__pb2.MoveRequest.SerializeToString,
            disttag__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/disttag.RegionServer/AddPlayer',
            disttag__pb2.PlayerState.SerializeToString,
            disttag__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/disttag.RegionServer/RemovePlayer',
            disttag__pb2.PlayerId.SerializeToString,
            disttag__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
