# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: disttag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'disttag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdisttag.proto\x12\x07\x64isttag\"\x07\n\x05\x45mpty\"\x1a\n\nPlayerInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\"E\n\x0cJoinResponse\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x13\n\x0bregion_addr\x18\x02 \x01(\t\x12\r\n\x05is_it\x18\x03 \x01(\x08\"\x1b\n\x06ItInfo\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"8\n\x0bMoveRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\n\n\x02\x64x\x18\x02 \x01(\x05\x12\n\n\x02\x64y\x18\x03 \x01(\x05\"4\n\x0cMoveResponse\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x0e\n\x06tagged\x18\x03 \x01(\x08\"6\n\x0bPlayerState\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\"\x1d\n\x08PlayerId\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"*\n\x08TagEvent\x12\x0e\n\x06tagger\x18\x01 \x01(\t\x12\x0e\n\x06tagged\x18\x02 \x01(\t\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa2\x01\n\nGameMaster\x12\x36\n\x08JoinGame\x12\x13.disttag.PlayerInfo\x1a\x15.disttag.JoinResponse\x12,\n\tReportTag\x12\x11.disttag.TagEvent\x1a\x0c.disttag.Ack\x12.\n\x0bGetItPlayer\x12\x0e.disttag.Empty\x1a\x0f.disttag.ItInfo2\xa5\x01\n\x0cRegionServer\x12\x33\n\x04Move\x12\x14.disttag.MoveRequest\x1a\x15.disttag.MoveResponse\x12/\n\tAddPlayer\x12\x14.disttag.PlayerState\x1a\x0c.disttag.Ack\x12/\n\x0cRemovePlayer\x12\x11.disttag.PlayerId\x1a\x0c.disttag.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'disttag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_PLAYERINFO']._serialized_start=35
  _globals['_PLAYERINFO']._serialized_end=61
  _globals['_JOINRESPONSE']._serialized_start=63
  _globals['_JOINRESPONSE']._serialized_end=132
  _globals['_ITINFO']._serialized_start=134
  _globals['_ITINFO']._serialized_end=161
  _globals['_MOVEREQUEST']._serialized_start=163
  _globals['_MOVEREQUEST']._serialized_end=219
  _globals['_MOVERESPONSE']._serialized_start=221
  _globals['_MOVERESPONSE']._serialized_end=273
  _globals['_PLAYERSTATE']._serialized_start=275
  _globals['_PLAYERSTATE']._serialized_end=329
  _globals['_PLAYERID']._serialized_start=331
  _globals['_PLAYERID']._serialized_end=360
  _globals['_TAGEVENT']._serialized_start=362
  _globals['_TAGEVENT']._serialized_end=404
  _globals['_ACK']._serialized_start=406
  _globals['_ACK']._serialized_end=427
  _globals['_GAMEMASTER']._serialized_start=430
  _globals['_GAMEMASTER']._serialized_end=592
  _globals['_REGIONSERVER']._serialized_start=595
  _globals['_REGIONSERVER']._serialized_end=760
# @@protoc_insertion_point(module_scope)
