# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x19\n\x06Result\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32U\n\x0e\x45xampleService\x12\x1f\n\nGetMessage\x12\x05.Name\x1a\x08.Message\"\x00\x12\"\n\x0bSendMessage\x12\x08.Message\x1a\x07.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAME']._serialized_start=17
  _globals['_NAME']._serialized_end=37
  _globals['_MESSAGE']._serialized_start=39
  _globals['_MESSAGE']._serialized_end=62
  _globals['_RESULT']._serialized_start=64
  _globals['_RESULT']._serialized_end=89
  _globals['_EXAMPLESERVICE']._serialized_start=91
  _globals['_EXAMPLESERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
