# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\"\x1b\n\nSensorData\x12\r\n\x05value\x18\x01 \x01(\x02\"4\n\x07Summary\x12\x0f\n\x07\x61verage\x18\x01 \x01(\x02\x12\x0b\n\x03min\x18\x02 \x01(\x02\x12\x0b\n\x03max\x18\x03 \x01(\x02\x32\x38\n\rSensorService\x12\'\n\x0cSendReadings\x12\x0b.SensorData\x1a\x08.Summary(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=16
  _globals['_SENSORDATA']._serialized_end=43
  _globals['_SUMMARY']._serialized_start=45
  _globals['_SUMMARY']._serialized_end=97
  _globals['_SENSORSERVICE']._serialized_start=99
  _globals['_SENSORSERVICE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
