# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: binary_search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'binary_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62inary_search.proto\x12\x0c\x62inarysearch\"6\n\x13\x42inarySearchRequest\x12\x10\n\x08\x65lements\x18\x01 \x03(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\"%\n\x14\x42inarySearchResponse\x12\r\n\x05index\x18\x01 \x01(\x05\x32n\n\x13\x42inarySearchService\x12W\n\x0c\x42inarySearch\x12!.binarysearch.BinarySearchRequest\x1a\".binarysearch.BinarySearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'binary_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BINARYSEARCHREQUEST']._serialized_start=37
  _globals['_BINARYSEARCHREQUEST']._serialized_end=91
  _globals['_BINARYSEARCHRESPONSE']._serialized_start=93
  _globals['_BINARYSEARCHRESPONSE']._serialized_end=130
  _globals['_BINARYSEARCHSERVICE']._serialized_start=132
  _globals['_BINARYSEARCHSERVICE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
