# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import binary_search_pb2 as binary__search__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in binary_search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BinarySearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BinarySearch = channel.unary_unary(
                '/binarysearch.BinarySearchService/BinarySearch',
                request_serializer=binary__search__pb2.BinarySearchRequest.SerializeToString,
                response_deserializer=binary__search__pb2.BinarySearchResponse.FromString,
                _registered_method=True)


class BinarySearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BinarySearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BinarySearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BinarySearch': grpc.unary_unary_rpc_method_handler(
                    servicer.BinarySearch,
                    request_deserializer=binary__search__pb2.BinarySearchRequest.FromString,
                    response_serializer=binary__search__pb2.BinarySearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'binarysearch.BinarySearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('binarysearch.BinarySearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BinarySearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BinarySearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/binarysearch.BinarySearchService/BinarySearch',
            binary__search__pb2.BinarySearchRequest.SerializeToString,
            binary__search__pb2.BinarySearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
