# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'prime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprime.proto\"\x1e\n\x0cPrimeRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"1\n\rPrimeResponse\x12\x10\n\x08is_prime\x18\x01 \x01(\x08\x12\x0e\n\x06number\x18\x02 \x01(\x03\x32;\n\x0cPrimeService\x12+\n\nCheckPrime\x12\r.PrimeRequest\x1a\x0e.PrimeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRIMEREQUEST']._serialized_start=15
  _globals['_PRIMEREQUEST']._serialized_end=45
  _globals['_PRIMERESPONSE']._serialized_start=47
  _globals['_PRIMERESPONSE']._serialized_end=96
  _globals['_PRIMESERVICE']._serialized_start=98
  _globals['_PRIMESERVICE']._serialized_end=157
# @@protoc_insertion_point(module_scope)
