# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datetime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'datetime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tetime.proto\"\x11\n\x0f\x44\x61teTimeRequest\"%\n\x10\x44\x61teTimeResponse\x12\x11\n\tdate_time\x18\x01 \x01(\t2E\n\x0f\x44\x61teTimeService\x12\x32\n\x0bGetDateTime\x12\x10.DateTimeRequest\x1a\x11.DateTimeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datetime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATETIMEREQUEST']._serialized_start=18
  _globals['_DATETIMEREQUEST']._serialized_end=35
  _globals['_DATETIMERESPONSE']._serialized_start=37
  _globals['_DATETIMERESPONSE']._serialized_end=74
  _globals['_DATETIMESERVICE']._serialized_start=76
  _globals['_DATETIMESERVICE']._serialized_end=145
# @@protoc_insertion_point(module_scope)
