# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lamportclock.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lamportclock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12lamportclock.proto\x12\x0clamportclock\"8\n\x0fResourceRequest\x12\x12\n\nprocess_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"P\n\rResourceReply\x12\x0f\n\x07granted\x18\x01 \x01(\x08\x12.\n\x07waiting\x18\x02 \x03(\x0b\x32\x1d.lamportclock.ResourceRequest\"8\n\x0fResourceRelease\x12\x12\n\nprocess_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\x07\n\x05\x45mpty2\x98\x01\n\x0cLamportClock\x12G\n\x07Request\x12\x1d.lamportclock.ResourceRequest\x1a\x1b.lamportclock.ResourceReply\"\x00\x12?\n\x07Release\x12\x1d.lamportclock.ResourceRelease\x1a\x13.lamportclock.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lamportclock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCEREQUEST']._serialized_start=36
  _globals['_RESOURCEREQUEST']._serialized_end=92
  _globals['_RESOURCEREPLY']._serialized_start=94
  _globals['_RESOURCEREPLY']._serialized_end=174
  _globals['_RESOURCERELEASE']._serialized_start=176
  _globals['_RESOURCERELEASE']._serialized_end=232
  _globals['_EMPTY']._serialized_start=234
  _globals['_EMPTY']._serialized_end=241
  _globals['_LAMPORTCLOCK']._serialized_start=244
  _globals['_LAMPORTCLOCK']._serialized_end=396
# @@protoc_insertion_point(module_scope)
