# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nring.proto\"9\n\x0f\x45lectionMessage\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x65lection_id\x18\x02 \x01(\x05\"4\n\x0e\x45lectionResult\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x44\n\x0cRingElection\x12\x34\n\rStartElection\x12\x10.ElectionMessage\x1a\x0f.ElectionResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONMESSAGE']._serialized_start=14
  _globals['_ELECTIONMESSAGE']._serialized_end=71
  _globals['_ELECTIONRESULT']._serialized_start=73
  _globals['_ELECTIONRESULT']._serialized_end=125
  _globals['_RINGELECTION']._serialized_start=127
  _globals['_RINGELECTION']._serialized_end=195
# @@protoc_insertion_point(module_scope)
